In [34]:
import numpy as np
import pandas as pd

In [35]:
date = pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day34-handling-date-and-time/orders.csv")
time = pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day34-handling-date-and-time/messages.csv")

In [36]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [37]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [38]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [39]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working With Dates

In [40]:
# converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [41]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

1. Extract Year

In [42]:
date['date_year'] = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

2. Extract Month

In [43]:
date['date_month_no'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

3. Extract Days

In [44]:
date['date_day'] = date['date'].dt.day
date.head()

        date  product_id  city_id  orders  date_year  date_month_no  date_day
0 2019-12-10        5628       25       3       2019             12        10
1 2018-08-15        3646       14     157       2018              8        15
2 2018-10-23        1859       25       1       2018             10        23
3 2019-08-17        7292       25       1       2019              8        17
4 2019-01-06        4344       25       3       2019              1         6

In [45]:
# day of week
date['date_low'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,date_low
0,2019-12-10,5628,25,3,2019,12,10,1
1,2018-08-15,3646,14,157,2018,8,15,2
2,2018-10-23,1859,25,1,2018,10,23,1
3,2019-08-17,7292,25,1,2019,8,17,5
4,2019-01-06,4344,25,3,2019,1,6,6

In [46]:
# day of week by name

date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month_no  date_day  date_low date_dow_name
0 2019-12-10       2019             12        10         1       Tuesday
1 2018-08-15       2018              8        15         2     Wednesday
2 2018-10-23       2018             10        23         1       Tuesday
3 2019-08-17       2019              8        17         5      Saturday
4 2019-01-06       2019              1         6         6        Sunday

In [47]:
# is weekend

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']),1,0)
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_low,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,10,1,Tuesday,0
1,2018-08-15,2018,8,15,2,Wednesday,0
2,2018-10-23,2018,10,23,1,Tuesday,0
3,2019-08-17,2019,8,17,5,Saturday,1
4,2019-01-06,2019,1,6,6,Sunday,1

4. Extract Week of the year

In [48]:
date['date-week'] = date['date'].dt.weekday
date.drop(columns=['product_id','city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_low,date_dow_name,date_is_weekend,date-week
0,2019-12-10,2019,12,10,1,Tuesday,0,1
1,2018-08-15,2018,8,15,2,Wednesday,0,2
2,2018-10-23,2018,10,23,1,Tuesday,0,1
3,2019-08-17,2019,8,17,5,Saturday,1,5
4,2019-01-06,2019,1,6,6,Sunday,1,6

5. Extract Quater

In [49]:
date['Quater'] = date['date'].dt.quarter
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_low,date_dow_name,date_is_weekend,date-week,Quater
0,2019-12-10,2019,12,10,1,Tuesday,0,1,4
1,2018-08-15,2018,8,15,2,Wednesday,0,2,3
2,2018-10-23,2018,10,23,1,Tuesday,0,1,4
3,2019-08-17,2019,8,17,5,Saturday,1,5,3
4,2019-01-06,2019,1,6,6,Sunday,1,6,1

6. Extract Semester

In [50]:
date['semester'] = np.where(date['Quater'].isin([1,2]),1,2)
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_low,date_dow_name,date_is_weekend,date-week,Quater,semester
0,2019-12-10,2019,12,10,1,Tuesday,0,1,4,2
1,2018-08-15,2018,8,15,2,Wednesday,0,2,3,2
2,2018-10-23,2018,10,23,1,Tuesday,0,1,4,2
3,2019-08-17,2019,8,17,5,Saturday,1,5,3,2
4,2019-01-06,2019,1,6,6,Sunday,1,6,1,1

7. Extract Time elapsed between dates

In [51]:
import datetime

today = datetime.datetime.today()
today

datetime.datetime(2026, 4, 25, 17, 57, 31, 941788)

In [52]:
(today - date['date']).dt.days

0      2328
1      2810
2      2741
3      2443
4      2666
       ...
995    2756
996    2697
997    2545
998    2610
999    2384
Name: date, Length: 1000, dtype: int64

In [55]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [56]:
# converting to datetime datatype

time['date'] = pd.to_datetime(time['date'])

time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [57]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['second'] = time['date'].dt.second

time.head()

,date,msg,hour,min,second
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

Time Difference

In [58]:
today -time['date']

0     4514 days 17:07:31.941788
1     4378 days 18:17:31.941788
2     4864 days 17:36:31.941788
3     4166 days 17:26:31.941788
4     4563 days 18:46:31.941788
                 ...
995   5153 days 17:07:31.941788
996   4474 days 18:43:31.941788
997   4939 days 18:20:31.941788
998   5055 days 18:23:31.941788
999   4327 days 18:32:31.941788
Name: date, Length: 1000, dtype: timedelta64[ns]